// Auto-generated from kenya-locations dataset. Do not edit manually.
export const KENYA_COUNTIES: string[] = ["Nairobi", "Kajiado", "Kiambu", "Mombasa", "Nakuru", "Baringo", "Bomet", "Bungoma", "Busia", "Elgeyo-Marakwet", "Embu", "Garissa", "Homa Bay", "Isiolo", "Kakamega", "Kericho", "Kilifi", "Kirinyaga", "Kisii", "Kisumu", "Kitui", "Kwale", "Laikipia", "Lamu", "Machakos", "Makueni", "Mandera", "Marsabit", "Meru", "Migori", "Murang'a", "Nandi", "Narok", "Nyamira", "Nyandarua", "Nyeri", "Samburu", "Siaya", "Taita Taveta", "Tana River", "Tharaka Nithi", "Trans Nzoia", "Turkana", "Uasin Gishu", "Vihiga", "Wajir", "West Pokot"];

export const KENYA_SUBLOCATIONS: Record<string, string[]> = {
  "Nairobi": [
    "Embakasi",
    "Karen",
    "Kilimani",
    "Nairobi Central",
    "Ngara",
    "Airbase",
    "Baba Dogo",
    "California",
    "Chokaa",
    "Clay City",
    "Dagoretti",
    "Dandora",
    "Donholm",
    "Eastleigh",
    "Gikomba/Kamukunji",
    "Githurai",
    "Huruma",
    "Imara Daima",
    "Industrial Area Nairobi",
    "Jamhuri",
    "Kabiro",
    "Kahawa",
    "Kahawa West",
    "Kamulu",
    "Kangemi",
    "Kariobangi",
    "Kasarani",
    "Kawangware",
    "Kayole",
    "Kiamaiko",
    "Kibra",
    "Kileleshwa",
    "Kitisuru",
    "Komarock",
    "Landimawe",
    "Langata",
    "Lavington",
    "Lucky Summer",
    "Makadara",
    "Makongeni",
    "Maringo/Hamza",
    "Mathare Hospital",
    "Mathare North",
    "Mbagathi Way",
    "Mlango Kubwa",
    "Mombasa Road",
    "Mountain View",
    "Mowlem",
    "Muthaiga",
    "Mwiki",
    "Nairobi South",
    "Nairobi West",
    "Njiru",
    "Pangani",
    "Parklands/Highridge",
    "Pumwani",
    "Ridgeways",
    "Roysambu",
    "Ruai",
    "Ruaraka",
    "Runda",
    "Saika",
    "South B",
    "South C",
    "Thome",
    "Umoja",
    "Upperhill",
    "Utalii",
    "Utawala",
    "Westlands",
    "Woodley/Kenyatta Golf Course",
    "Zimmerman",
    "Ziwani/Kariokor"
  ],
  "Kajiado": [
    "Kitengela",
    "Ngong",
    "Ongata Rongai",
    "Bisil",
    "DalaleKutuk",
    "Emurua Dikir",
    "Entonet/Lenkisim",
    "Eselenkei",
    "Ewaso Kendong",
    "Ewuaso Oonkidong'I",
    "Ildamat",
    "Iloodokilani / Amboseli",
    "Imaroro",
    "Isinya",
    "Kajiado CBD",
    "Kenyawa-Poka",
    "Kimana",
    "Kisaju",
    "Kiserian",
    "Kuku",
    "Kumpa",
    "Loitoktok",
    "Magadi",
    "Mata",
    "Matapato",
    "Mbirikani",
    "Mosiro",
    "Namanga",
    "Olkeri",
    "Oloika",
    "Oloolua",
    "Oloosirkon/Sholinke",
    "Purko",
    "Rombo"
  ],
  "Kiambu": [
    "Juja",
    "Kiambu / Kiambu",
    "Kikuyu",
    "Ruiru",
    "Thika",
    "Banana",
    "Gachie",
    "Gatundu North",
    "Gatundu South",
    "Gitaru",
    "Githunguri",
    "Kabete",
    "Kiambaa",
    "Lari",
    "Limuru",
    "Nachu",
    "Ndenderu",
    "Nyadhuna",
    "Rosslyn",
    "Ruaka",
    "Turitu",
    "Witeithie"
  ],
  "Mombasa": [
    "Kisauni",
    "Mombasa CBD",
    "Mvita",
    "Nyali",
    "Tudor",
    "Bamburi",
    "Chaani",
    "Changamwe",
    "Ganjoni",
    "Industrial Area (Msa)",
    "Jomvu",
    "Kikowani",
    "Kizingo",
    "Likoni",
    "Makadara (Msa)",
    "Mbaraki",
    "Old Town",
    "Shanzu",
    "Shimanzi",
    "Tononoka"
  ],
  "Nakuru": [
    "Naivasha",
    "Nakuru Town East",
    "Bahati",
    "Gilgil",
    "Hells Gate",
    "Kuresoi North",
    "Kuresoi South",
    "Lanet",
    "London",
    "Maiella",
    "Malewa West",
    "Mbaruk/Eburu",
    "Molo",
    "Nakuru Town West",
    "Njoro",
    "Olkaria",
    "Rongai",
    "Salgaa",
    "Subukia"
  ],
  "Baringo": [
    "Kabarnet",
    "Marigat",
    "Ravine",
    "Bartabwa",
    "Barwessa",
    "Churo/Amaya",
    "Emining",
    "Ewalel Chapchap",
    "Kapropita",
    "Kisanana",
    "Koibatek",
    "Lembus",
    "Lembus Kwen",
    "Lembus/Perkerra",
    "Mogotio",
    "Mukutani",
    "Nginyang East",
    "Nginyang West",
    "Sacho",
    "Silale",
    "Tenges"
  ],
  "Bomet": [
    "Chemagel",
    "Longisa",
    "Silibwet Township",
    "Boito",
    "Chebunyo",
    "Embomos",
    "Kapletundo",
    "Kembu",
    "Kimulot",
    "Kipsonoi",
    "Merigi",
    "Mogogosiek",
    "Mutarakwa",
    "Ndanai/Abosi",
    "Ndaraweta",
    "Nyangores",
    "Sigor",
    "Singorwet",
    "Siongiroi"
  ],
  "Bungoma": [
    "Kabuchai/Chwele",
    "Khalaba (Kanduyi)",
    "Marakaru/Tuuti",
    "Township D",
    "Bokoli",
    "Bukembe East",
    "Bukembe West",
    "Bumula",
    "Bwake/Luuya",
    "Cheptais",
    "Chepyuk",
    "East Sang'Alo",
    "Elgon",
    "Kabula",
    "Kamukuywa",
    "Kibingei",
    "Kimaeti",
    "Kimilili",
    "Maeni",
    "Malakisi/South Kulisiru",
    "Maraka",
    "Matulo",
    "Mihuu",
    "Misikhu",
    "Musikoma",
    "Namwela",
    "Ndalu/Tabani",
    "Siboti",
    "Sirisia",
    "Sitikho",
    "South Bukusu",
    "Soysambu/Mitua",
    "Tongaren",
    "Webuye",
    "West Bukusu",
    "West Nalondo",
    "West Sang'Alo"
  ],
  "Busia": [
    "Ageng'A Nanguba",
    "Bunyala West (Budalangi)",
    "Burumba",
    "Amukura Central",
    "Amukura East",
    "Amukura West",
    "Ang'Orom",
    "Bukhayo Central",
    "Bukhayo East",
    "Bukhayo West",
    "Bunyala Central (Budalangi)",
    "Bunyala North",
    "Busibwabo",
    "Bwiri",
    "Elugulu",
    "Kingandole",
    "Malaba Central",
    "Malaba North",
    "Marachi Central",
    "Marachi East",
    "Marachi West",
    "Matayos South",
    "Mayenje",
    "Nambale Township",
    "Nangina"
  ],
  "Elgeyo-Marakwet": [
    "Arror",
    "Chepkorio",
    "Emsoo",
    "Endo",
    "Kamariny",
    "Kapchemutwa",
    "Kaptarakwa",
    "Metkei",
    "Moiben/Kuserwo",
    "Sengwer",
    "Soy North",
    "Tambach"
  ],
  "Embu": [
    "Central Ward",
    "Kirimari",
    "Mwea",
    "Evurore",
    "Gaturi North",
    "Gaturi South",
    "Kagaari North",
    "Kagaari South",
    "Kiambere",
    "Kithimu",
    "Kyeni North",
    "Kyeni South",
    "Makima",
    "Mavuria",
    "Mbeti North",
    "Mbeti South",
    "Muminji",
    "Nginda",
    "Nthawa",
    "Ruguru/Ngandori"
  ],
  "Garissa": [
    "Dadaab",
    "Iftin",
    "Abakaile",
    "Bura",
    "Damajale",
    "Galbet",
    "Goreale",
    "Ijara",
    "Jara Jara",
    "Labasigale",
    "Liboi",
    "Masalani",
    "Sankuri",
    "Waberi"
  ],
  "Homa Bay": [
    "Homa Bay Central",
    "Mfangano Island",
    "Central Karachuonyo",
    "Central Kasipul",
    "East Gem (Rangwe)",
    "East Kamagak",
    "Gembe",
    "Homa Bay Arujo",
    "Homa Bay East",
    "Homa Bay West",
    "Kabondo East",
    "Kagan",
    "Kaksingri West",
    "Kanyadoto",
    "Kanyaluo",
    "Kanyamwa Kologi",
    "Kanyamwa Kosewe",
    "Kanyikela",
    "Kasgunga",
    "Kendu Bay Town",
    "Kochia",
    "Kwabwai",
    "Lambwe",
    "North Karachuonyo",
    "Rusinga Island",
    "South Kasipul",
    "West Kamagak",
    "West Kasipul"
  ],
  "Isiolo": [
    "Bulla Pesa",
    "Burat",
    "Garba Tulla",
    "Isiolo North",
    "Kinna",
    "Oldonyiro",
    "Wabera"
  ],
  "Kakamega": [
    "Mumias Central",
    "Sheywe",
    "Bunyala Central (Navakholo)",
    "Bunyala East",
    "Bunyala West (Navakholo)",
    "Butali/Chegulo",
    "Butsotso Central",
    "Butsotso East",
    "Butsotso South",
    "Chekalini",
    "Chemuche",
    "Chevaywa",
    "East Kabras",
    "East Wanga",
    "Etenje",
    "Idakho Central",
    "Idakho East",
    "Idakho South",
    "Ingostse-Mathia",
    "Isukha Central",
    "Isukha East",
    "Isukha North",
    "Isukha South",
    "Isukha West",
    "Khalaba (Matungu)",
    "Kholera",
    "Kisa Central",
    "Kisa East",
    "Kisa North",
    "Kisa West",
    "Kongoni",
    "Koyonzo",
    "Likuyani",
    "Lugari",
    "Lumakanda",
    "Lusheya/Lubinu",
    "Lwandeti",
    "Mahiakalo",
    "Malaha/Isongo/Makunga",
    "Marama Central",
    "Marama North",
    "Marama South",
    "Marama West",
    "Marenyo-Shianda",
    "Mautuma",
    "Mayoni",
    "Murhanda",
    "Musanda",
    "Nzoia",
    "Sango",
    "Shinoyi-Shikomari-Esumeyia",
    "Shirere",
    "Shirugu-Mugai",
    "Sinoko",
    "South Kabras",
    "West Kabras"
  ],
  "Kericho": [
    "Ainamoi",
    "Litein",
    "Chaik",
    "Cheboin",
    "Chemosot",
    "Cheplanget",
    "Chepseon",
    "Cheptororiet/Seretut",
    "Chilchila",
    "Kabianga",
    "Kamasian",
    "Kapkatet",
    "Kapkugerwet",
    "Kapsaos (Ainamoi)",
    "Kapsoit",
    "Kapsuser",
    "Kedowa/Kimugul",
    "Kipchebor",
    "Kipchimchim",
    "Kipkelion",
    "Londiani",
    "Sigowet",
    "Soin (Sigowet)",
    "Tebesonik",
    "Waldai"
  ],
  "Kilifi": [
    "Kilifi North",
    "Malindi",
    "Mtwapa",
    "Ganze",
    "Kaloleni",
    "Kambe/Ribe",
    "Kilifi South",
    "Kilifi Town",
    "Magarini",
    "Rabai"
  ],
  "Kirinyaga": [
    "Kerugoya",
    "Kiine",
    "Baragwi",
    "Gathigiriri",
    "Inoi",
    "Kabare",
    "Kangai",
    "Kanyekini",
    "Kariti",
    "Karumandi",
    "Mukure",
    "Murinduko",
    "Mutira",
    "Mutithi",
    "Ngariama",
    "Njukiini",
    "Nyangati",
    "Tebere",
    "Thiba",
    "Wamumu"
  ],
  "Kisii": [
    "Kisii CBD",
    "Basi Bogetaorio",
    "Bobasi",
    "Bomachoge Borabu",
    "Bomachoge Chache",
    "Bonchari",
    "Kitutu Chache South",
    "Marani",
    "Monyerero",
    "Nyaribari Chache",
    "Nyaribari Masaba",
    "Ogembo",
    "South Mugirango",
    "Suneka"
  ],
  "Kisumu": [
    "Kisumu Central",
    "Kisumu West",
    "Chemelil",
    "Kaloleni",
    "Kisumu East",
    "Kolwa Central",
    "Kolwa East",
    "Muhoroni",
    "North West Kisumu",
    "Nyakach",
    "Nyando",
    "Seme",
    "South West Kisumu"
  ],
  "Kitui": [
    "Central Mwingi",
    "Township",
    "Athi",
    "Chuluni",
    "Endau/Malalani",
    "Ikanga/Kyatune",
    "Kanyangi",
    "Kauwi",
    "Kiomo/Kyethani",
    "Kisasi",
    "Kwa Mutonga/Kithumula",
    "Kwavonza/Yatta",
    "Kyangwithya East",
    "Kyangwithya West",
    "Kyome/Thaana",
    "Kyuso",
    "Matinyani",
    "Mbitini",
    "Migwani",
    "Mulango",
    "Mutito/Kaliku",
    "Mutomo",
    "Mutonguni",
    "Ngomeni",
    "Nguni",
    "Nguutani",
    "Nzambani",
    "Tseikuru",
    "Zombe/Mwitika"
  ],
  "Kwale": [
    "Ukunda",
    "Chengoni/Samburu",
    "Diani",
    "Dzombo",
    "Gombato Bongwe",
    "Kinango",
    "Kinondo",
    "Kubo South",
    "Mackinnon Road",
    "Mazeras",
    "Mkongani",
    "Mwavumbo",
    "Mwereni",
    "Ndavaya",
    "Pongwe/Kikoneni",
    "Ramisi",
    "Tiwi",
    "Tsimba Golini",
    "Vanga",
    "Waa"
  ],
  "Laikipia": [
    "Nanyuki",
    "Githiga (Laikipia)",
    "Laikipia Central",
    "Laikipia East",
    "Laikipia North",
    "Laikipia West",
    "Mukogondo East",
    "Nyahururu"
  ],
  "Lamu": [
    "Mkomani",
    "Bahari",
    "Faza",
    "Hindi",
    "Hongwe",
    "Shella",
    "Witu"
  ],
  "Machakos": [
    "Athi River",
    "Machakos Town",
    "Syokimau",
    "Kangundo",
    "Kathiani",
    "Lower Kaewa/Kaani",
    "Masinga",
    "Matungulu",
    "Mavoko",
    "Mlolongo",
    "Mua",
    "Mwala",
    "Upper Kaewa/Iveti",
    "Yatta"
  ],
  "Makueni": [
    "Emali/Mulala",
    "Makindu",
    "Wote",
    "Ilima",
    "Ivingoni/Nzambani",
    "Kasikeu",
    "Kathonzweni",
    "Kiima Kiu/Kalanzoni",
    "Kikumbulyu North",
    "Kikumbulyu South",
    "Kilungu",
    "Kisau-Kiteta",
    "Kithungo/Kitundu",
    "Masongaleni",
    "Mavindini",
    "Mbitini",
    "Mbooni",
    "Mtito Andei",
    "Mukaa",
    "Muvau/Kikuumini",
    "Nguu/Masumba",
    "Nguumo",
    "Nzaui/Kilili/Kalamba",
    "Thange",
    "Tulimani",
    "Ukia",
    "Waia/Kako"
  ],
  "Mandera": [
    "Elwak North",
    "Township"
  ],
  "Marsabit": [
    "Butiye",
    "Marsabit Central",
    "Moyale Township"
  ],
  "Meru": [
    "Maua",
    "Municipality",
    "Abogeta East",
    "Abogeta West",
    "Abothuguchi Central",
    "Akirang'Ondu",
    "Akithii",
    "Amwathi",
    "Antubetwe Kiongo",
    "Athiru Gaiti",
    "Athiru Ruujine",
    "Athwana",
    "Igembe East",
    "Igoji East",
    "Igoji West",
    "Kangeta",
    "Karama",
    "Kiagu",
    "Kianjai",
    "Kibirichia",
    "Kiirua/Naari",
    "Kisima",
    "Mbeu",
    "Meru Town",
    "Mikinduri",
    "Mitunguu",
    "Muthara",
    "Mwanganthia",
    "Nkomo",
    "Nkubu",
    "Nkuene",
    "Ntima East",
    "Ntima West",
    "Nyaki East",
    "Nyaki West",
    "Ruiri/Rwarera",
    "Timau"
  ],
  "Migori": [
    "Bukira Central/Ikerege",
    "Bukira East",
    "Central Kamagambo",
    "Central Kanyamkago",
    "Central Sakwa (Awendo)",
    "East Kamagambo",
    "East Kanyamkago",
    "God Jope",
    "Isibania",
    "Kachien'G A",
    "Kakrao",
    "Kwa",
    "Makerero",
    "Muhuru",
    "North Kadem",
    "North Kamagambo",
    "North Sakwa (Awendo)",
    "Ntimaru West",
    "Ragana-Oruba",
    "South Kamagambo",
    "South Sakwa (Awendo)",
    "Suna Central",
    "Tagare",
    "Wasweta II",
    "West Sakwa (Awendo)"
  ],
  "Murang'a": [
    "Gatanga",
    "Kimorori/Wempa",
    "Makuyu",
    "Township G",
    "Gaichanjiru",
    "Gaturi",
    "Gitugi",
    "Ichagaki",
    "Ithanga",
    "Ithiru",
    "Kagundu-Ini",
    "Kahumbu",
    "Kakuzi/Mitubiri",
    "Kamacharia",
    "Kamahuha",
    "Kambiti",
    "Kangari",
    "Kanyenya-Ini",
    "Kariara",
    "Kigumo",
    "Kihumbu-Ini",
    "Kinyona",
    "Kiru",
    "Mbiri",
    "Mugoiri",
    "Mugumo-Ini",
    "Muguru",
    "Muruka",
    "Ng'Araria",
    "Nginda",
    "Ruchu",
    "Rwathia",
    "Wangu"
  ],
  "Nandi": [
    "Kapsabet",
    "Chemelil/Chemase",
    "Chemundu/Kapng'Etuny",
    "Chepkumia",
    "Chepkunyuk",
    "Kabisaga",
    "Kabiyet",
    "Kapkangani",
    "Kaptel/Kamoiywo",
    "Kaptumo-Kaboi",
    "Kemeloi-Maraba",
    "Kilibwoni",
    "Kipkaren",
    "Kiptuya",
    "Kobujoi",
    "Kosirai",
    "Nandi Hills",
    "Ndalat",
    "Ol'Lessos",
    "Songhor/Soba",
    "Tindiret"
  ],
  "Narok": [
    "Narok Town",
    "Angata Barikoi",
    "Ildamat (Narok)",
    "Ilkerin",
    "Ilmotiok",
    "Kapsasian",
    "Keekonyokie (Narok)",
    "Keyian",
    "Kilgoris Central",
    "Kimintet",
    "Lolgorian",
    "Majimoto/Naroosura",
    "Mara",
    "Melelo",
    "Melili",
    "Mosiro (Narok)",
    "Naikarra",
    "Olokurto",
    "Ololmasani",
    "Ololulung'A",
    "Olorropil",
    "Olpusimoru",
    "Siana",
    "Suswa"
  ],
  "Nyamira": [
    "Bogichora",
    "Bokeira",
    "Bonyamatuta",
    "Esise",
    "Gachuba",
    "Gesima",
    "Kemera",
    "Kiabonyoru",
    "Magwagwa",
    "Manga",
    "Nyamaiya",
    "Nyansiongo",
    "Rigoma",
    "Township F"
  ],
  "Nyandarua": [
    "Karau",
    "Magumu",
    "Central Ndaragwa",
    "Charagita",
    "Engineer",
    "Gathanji",
    "Gathara",
    "Gatimu",
    "Geta",
    "Githabai",
    "Githioro",
    "Kaimbaga",
    "Kanjuiri Range",
    "Kipipiri",
    "Kiriita",
    "Leshau Pondo",
    "Mirangine",
    "Murungaru",
    "NjabiniKiburu",
    "North Kinangop",
    "Nyakio",
    "Rurii",
    "Shamata",
    "Wanjohi",
    "Weru"
  ],
  "Nyeri": [
    "Karatina Town",
    "Dedan Kimanthi",
    "Iriaini",
    "Kieni",
    "Kirimukuyu",
    "Mathira",
    "Mukurwe-Ini Central",
    "Mukurwe-Ini West",
    "Mukurweini",
    "Naromoru Kiamathaga",
    "Nyeri Town",
    "Othaya",
    "Tetu",
    "Thegu River"
  ],
  "Samburu": [
    "Angata Nanyokie",
    "Loosuk",
    "Maralal",
    "Suguta Marmar",
    "Wamba East",
    "Waso"
  ],
  "Siaya": [
    "Siaya Township",
    "Central Gem",
    "Central Sakwa (Bondo)",
    "East Asembo",
    "East Gem",
    "East Ugenya",
    "North Gem",
    "North Sakwa (Bondo)",
    "North Ugenya",
    "North Uyoma",
    "Sidindi",
    "Sigomere",
    "South East Alego",
    "South Gem",
    "South Sakwa (Bondo)",
    "Ugunja",
    "Ukwala",
    "West Alego",
    "West Asembo",
    "West Gem",
    "West Sakwa (Bondo)",
    "West Ugenya",
    "West Uyoma",
    "Yala Township",
    "Yimbo West"
  ],
  "Taita Taveta": [
    "Bura (Mwatate)",
    "Chala",
    "Kaloleni",
    "Kasigau",
    "Mahoo",
    "Mata",
    "Mboghoni",
    "Mbololo",
    "Mwatate",
    "Ngolia",
    "Sagala",
    "Werugha",
    "Wumingu/Kishushe",
    "Wundanyi/Mbale"
  ],
  "Tana River": [
    "Bura",
    "Chewani",
    "Garsen Central",
    "Kinakomba",
    "Kipini East",
    "Kipini West",
    "Madogo",
    "Mikinduni",
    "Wayu"
  ],
  "Tharaka Nithi": [
    "Igambang'Ombe",
    "Chiakariga",
    "Chogoria",
    "Ganga",
    "Gatunga",
    "Karingani",
    "Magumoni",
    "Mariani",
    "Mitheru",
    "Mugwe",
    "Mukothima",
    "Muthambi"
  ],
  "Trans Nzoia": [
    "Kitale",
    "Bidii",
    "Chepchoina",
    "Chepsiro/Kiptoror",
    "Cherangany/Suwerwa",
    "Endebess",
    "Hospital (Kiminini)",
    "Kaplamai",
    "Keiyo",
    "Kiminini",
    "Kinyoro",
    "Kwanza",
    "Makutano",
    "Matisi",
    "Motosiet",
    "Nabiswa",
    "Saboti",
    "Sikhendu",
    "Sinyerere",
    "Sirende",
    "Sitatunga",
    "Tuwani",
    "Waitaluk"
  ],
  "Turkana": [
    "Lodwar Township",
    "Kakuma",
    "Kanamkemer",
    "Katilia",
    "Kerio Delta",
    "Kibish",
    "Lokichar",
    "Lokichoggio",
    "Turkwel"
  ],
  "Uasin Gishu": [
    "Eldoret CBD",
    "Ainabkoi",
    "Kapseret",
    "Kesses",
    "Moiben",
    "Soy",
    "Turbo"
  ],
  "Vihiga": [
    "Central Bunyore",
    "Central Maragoli",
    "Chavakali",
    "Luanda Township",
    "Banja",
    "Emabungo",
    "Luanda South",
    "Lugaga-Wamuluma",
    "Lyaduywa/Izava",
    "Muhudu",
    "Mwibona",
    "North East Bunyore",
    "North Maragoli",
    "Shamakhokho",
    "Shiru",
    "Tambua",
    "Wodanga"
  ],
  "Wajir": [
    "Barwago",
    "Godoma",
    "Habasswein",
    "Korondile",
    "Tarbaj",
    "Township"
  ],
  "West Pokot": [
    "Endugh",
    "Kapenguria",
    "Lomut",
    "Mnagei"
  ]
};

export const KENYA_ALL_LOCATIONS: string[] = Array.from(new Set([...KENYA_COUNTIES, ...Object.values(KENYA_SUBLOCATIONS).flat()])).sort();
