/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as MortgageRouteImport } from './routes/mortgage'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesValuationRouteImport } from './routes/services.valuation'
import { Route as ServicesSellRouteImport } from './routes/services.sell'
import { Route as ServicesRentRouteImport } from './routes/services.rent'
import { Route as ServicesMarketingRouteImport } from './routes/services.marketing'
import { Route as ServicesManagementRouteImport } from './routes/services.management'
import { Route as ServicesListRouteImport } from './routes/services.list'
import { Route as ServicesLeaseRouteImport } from './routes/services.lease'
import { Route as ServicesInvestmentRouteImport } from './routes/services.investment'
import { Route as ServicesBuyRouteImport } from './routes/services.buy'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as AuthenticatedSavedSearchesRouteImport } from './routes/_authenticated/saved-searches'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardNewRouteImport } from './routes/_authenticated/dashboard.new'
import { Route as AuthenticatedDashboardInquiriesRouteImport } from './routes/_authenticated/dashboard.inquiries'

const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const MortgageRoute = MortgageRouteImport.update({
  id: '/mortgage',
  path: '/mortgage',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesValuationRoute = ServicesValuationRouteImport.update({
  id: '/services/valuation',
  path: '/services/valuation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSellRoute = ServicesSellRouteImport.update({
  id: '/services/sell',
  path: '/services/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRentRoute = ServicesRentRouteImport.update({
  id: '/services/rent',
  path: '/services/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMarketingRoute = ServicesMarketingRouteImport.update({
  id: '/services/marketing',
  path: '/services/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesManagementRoute = ServicesManagementRouteImport.update({
  id: '/services/management',
  path: '/services/management',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesListRoute = ServicesListRouteImport.update({
  id: '/services/list',
  path: '/services/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLeaseRoute = ServicesLeaseRouteImport.update({
  id: '/services/lease',
  path: '/services/lease',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesInvestmentRoute = ServicesInvestmentRouteImport.update({
  id: '/services/investment',
  path: '/services/investment',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBuyRoute = ServicesBuyRouteImport.update({
  id: '/services/buy',
  path: '/services/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropertiesRoute,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSavedSearchesRoute =
  AuthenticatedSavedSearchesRouteImport.update({
    id: '/saved-searches',
    path: '/saved-searches',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardNewRoute =
  AuthenticatedDashboardNewRouteImport.update({
    id: '/dashboard/new',
    path: '/dashboard/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardInquiriesRoute =
  AuthenticatedDashboardInquiriesRouteImport.update({
    id: '/dashboard/inquiries',
    path: '/dashboard/inquiries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/mortgage': typeof MortgageRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/saved-searches': typeof AuthenticatedSavedSearchesRoute
  '/agents/$id': typeof AgentsIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/services/buy': typeof ServicesBuyRoute
  '/services/investment': typeof ServicesInvestmentRoute
  '/services/lease': typeof ServicesLeaseRoute
  '/services/list': typeof ServicesListRoute
  '/services/management': typeof ServicesManagementRoute
  '/services/marketing': typeof ServicesMarketingRoute
  '/services/rent': typeof ServicesRentRoute
  '/services/sell': typeof ServicesSellRoute
  '/services/valuation': typeof ServicesValuationRoute
  '/dashboard/inquiries': typeof AuthenticatedDashboardInquiriesRoute
  '/dashboard/new': typeof AuthenticatedDashboardNewRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/mortgage': typeof MortgageRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/saved-searches': typeof AuthenticatedSavedSearchesRoute
  '/agents/$id': typeof AgentsIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/services/buy': typeof ServicesBuyRoute
  '/services/investment': typeof ServicesInvestmentRoute
  '/services/lease': typeof ServicesLeaseRoute
  '/services/list': typeof ServicesListRoute
  '/services/management': typeof ServicesManagementRoute
  '/services/marketing': typeof ServicesMarketingRoute
  '/services/rent': typeof ServicesRentRoute
  '/services/sell': typeof ServicesSellRoute
  '/services/valuation': typeof ServicesValuationRoute
  '/dashboard/inquiries': typeof AuthenticatedDashboardInquiriesRoute
  '/dashboard/new': typeof AuthenticatedDashboardNewRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/mortgage': typeof MortgageRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/saved-searches': typeof AuthenticatedSavedSearchesRoute
  '/agents/$id': typeof AgentsIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/services/buy': typeof ServicesBuyRoute
  '/services/investment': typeof ServicesInvestmentRoute
  '/services/lease': typeof ServicesLeaseRoute
  '/services/list': typeof ServicesListRoute
  '/services/management': typeof ServicesManagementRoute
  '/services/marketing': typeof ServicesMarketingRoute
  '/services/rent': typeof ServicesRentRoute
  '/services/sell': typeof ServicesSellRoute
  '/services/valuation': typeof ServicesValuationRoute
  '/_authenticated/dashboard/inquiries': typeof AuthenticatedDashboardInquiriesRoute
  '/_authenticated/dashboard/new': typeof AuthenticatedDashboardNewRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/compare'
    | '/contact'
    | '/mortgage'
    | '/properties'
    | '/admin'
    | '/favorites'
    | '/saved-searches'
    | '/agents/$id'
    | '/properties/$id'
    | '/services/buy'
    | '/services/investment'
    | '/services/lease'
    | '/services/list'
    | '/services/management'
    | '/services/marketing'
    | '/services/rent'
    | '/services/sell'
    | '/services/valuation'
    | '/dashboard/inquiries'
    | '/dashboard/new'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/compare'
    | '/contact'
    | '/mortgage'
    | '/properties'
    | '/admin'
    | '/favorites'
    | '/saved-searches'
    | '/agents/$id'
    | '/properties/$id'
    | '/services/buy'
    | '/services/investment'
    | '/services/lease'
    | '/services/list'
    | '/services/management'
    | '/services/marketing'
    | '/services/rent'
    | '/services/sell'
    | '/services/valuation'
    | '/dashboard/inquiries'
    | '/dashboard/new'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blog'
    | '/compare'
    | '/contact'
    | '/mortgage'
    | '/properties'
    | '/_authenticated/admin'
    | '/_authenticated/favorites'
    | '/_authenticated/saved-searches'
    | '/agents/$id'
    | '/properties/$id'
    | '/services/buy'
    | '/services/investment'
    | '/services/lease'
    | '/services/list'
    | '/services/management'
    | '/services/marketing'
    | '/services/rent'
    | '/services/sell'
    | '/services/valuation'
    | '/_authenticated/dashboard/inquiries'
    | '/_authenticated/dashboard/new'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  MortgageRoute: typeof MortgageRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  AgentsIdRoute: typeof AgentsIdRoute
  ServicesBuyRoute: typeof ServicesBuyRoute
  ServicesInvestmentRoute: typeof ServicesInvestmentRoute
  ServicesLeaseRoute: typeof ServicesLeaseRoute
  ServicesListRoute: typeof ServicesListRoute
  ServicesManagementRoute: typeof ServicesManagementRoute
  ServicesMarketingRoute: typeof ServicesMarketingRoute
  ServicesRentRoute: typeof ServicesRentRoute
  ServicesSellRoute: typeof ServicesSellRoute
  ServicesValuationRoute: typeof ServicesValuationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mortgage': {
      id: '/mortgage'
      path: '/mortgage'
      fullPath: '/mortgage'
      preLoaderRoute: typeof MortgageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/valuation': {
      id: '/services/valuation'
      path: '/services/valuation'
      fullPath: '/services/valuation'
      preLoaderRoute: typeof ServicesValuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/sell': {
      id: '/services/sell'
      path: '/services/sell'
      fullPath: '/services/sell'
      preLoaderRoute: typeof ServicesSellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/rent': {
      id: '/services/rent'
      path: '/services/rent'
      fullPath: '/services/rent'
      preLoaderRoute: typeof ServicesRentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/marketing': {
      id: '/services/marketing'
      path: '/services/marketing'
      fullPath: '/services/marketing'
      preLoaderRoute: typeof ServicesMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/management': {
      id: '/services/management'
      path: '/services/management'
      fullPath: '/services/management'
      preLoaderRoute: typeof ServicesManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/list': {
      id: '/services/list'
      path: '/services/list'
      fullPath: '/services/list'
      preLoaderRoute: typeof ServicesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/lease': {
      id: '/services/lease'
      path: '/services/lease'
      fullPath: '/services/lease'
      preLoaderRoute: typeof ServicesLeaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/investment': {
      id: '/services/investment'
      path: '/services/investment'
      fullPath: '/services/investment'
      preLoaderRoute: typeof ServicesInvestmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/buy': {
      id: '/services/buy'
      path: '/services/buy'
      fullPath: '/services/buy'
      preLoaderRoute: typeof ServicesBuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/saved-searches': {
      id: '/_authenticated/saved-searches'
      path: '/saved-searches'
      fullPath: '/saved-searches'
      preLoaderRoute: typeof AuthenticatedSavedSearchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/new': {
      id: '/_authenticated/dashboard/new'
      path: '/dashboard/new'
      fullPath: '/dashboard/new'
      preLoaderRoute: typeof AuthenticatedDashboardNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/inquiries': {
      id: '/_authenticated/dashboard/inquiries'
      path: '/dashboard/inquiries'
      fullPath: '/dashboard/inquiries'
      preLoaderRoute: typeof AuthenticatedDashboardInquiriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedSavedSearchesRoute: typeof AuthenticatedSavedSearchesRoute
  AuthenticatedDashboardInquiriesRoute: typeof AuthenticatedDashboardInquiriesRoute
  AuthenticatedDashboardNewRoute: typeof AuthenticatedDashboardNewRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedSavedSearchesRoute: AuthenticatedSavedSearchesRoute,
  AuthenticatedDashboardInquiriesRoute: AuthenticatedDashboardInquiriesRoute,
  AuthenticatedDashboardNewRoute: AuthenticatedDashboardNewRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PropertiesRouteChildren {
  PropertiesIdRoute: typeof PropertiesIdRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesIdRoute: PropertiesIdRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  MortgageRoute: MortgageRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  AgentsIdRoute: AgentsIdRoute,
  ServicesBuyRoute: ServicesBuyRoute,
  ServicesInvestmentRoute: ServicesInvestmentRoute,
  ServicesLeaseRoute: ServicesLeaseRoute,
  ServicesListRoute: ServicesListRoute,
  ServicesManagementRoute: ServicesManagementRoute,
  ServicesMarketingRoute: ServicesMarketingRoute,
  ServicesRentRoute: ServicesRentRoute,
  ServicesSellRoute: ServicesSellRoute,
  ServicesValuationRoute: ServicesValuationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
