ALTER TABLE public.properties DROP COLUMN IF EXISTS business_id;
DROP TABLE IF EXISTS public.business_views CASCADE;
DROP TABLE IF EXISTS public.business_reviews CASCADE;
DROP TABLE IF EXISTS public.business_enquiries CASCADE;
DROP TABLE IF EXISTS public.business_claims CASCADE;
DROP TABLE IF EXISTS public.business_staff CASCADE;
DROP TABLE IF EXISTS public.businesses CASCADE;
DROP TABLE IF EXISTS public.business_categories CASCADE;
DROP TABLE IF EXISTS public.business_plans CASCADE;
DROP FUNCTION IF EXISTS public.can_manage_business(uuid, uuid) CASCADE;